bpmn-io/bpmn-js-examples

- custom-elements/README.md
- custom-elements/app/custom-modeler/custom/CustomOrderingProvider.js
- custom-elements/app/custom-modeler/custom/CustomUpdater.js
- custom-elements/app/custom-modeler/custom/index.js
- custom-elements/test/spec/Modeling.collaboration.bpmn
- custom-elements/test/spec/ModelingSpec.js
* showcase ordering provider
* integrate with Collaboration -> Process conversion
> Improve custom elements example

- properties-panel-extension/package.json
- properties-panel/package.json
> chore(project): update bpmn-js-properties-panel dependency

- i18n/README.md
- i18n/app/customTranslate/customTranslate.js
This reverts commit 33d2fe92fe00f69d1ed1ca80c4db17426e32b919.
Follow-up of https://github.com/bpmn-io/diagram-js/pull/365.
> Revert "feat(i18n): escape translations per default"

- bundling/README.md
- bundling/src/app.js
- colors/README.md
- colors/index.html
- commenting/.babelrc
- commenting/app/app.js
- custom-bundle/index.html
- custom-meta-model/.babelrc
- custom-meta-model/app/index.js
- i18n/app/app.js
- interaction/README.md
- interaction/index.html
- minimap/README.md
- minimap/app/app.js
- modeler/app/app.js
- overlays/README.md
- overlays/app/app.js
- pre-packaged/README.md
- properties-panel-extension/.babelrc
- properties-panel-extension/app/index.js
- properties-panel-extension/package.json
- properties-panel/app/index.js
- starter/modeler.html
- starter/viewer.html
- theming/index.html
- transaction-boundaries/.babelrc
- transaction-boundaries/README.md
- transaction-boundaries/app/index.js
- transaction-boundaries/package.json
- url-viewer/index.html
Will bump the bpmn-js versions / update related <script src="..."..> tags once we do the release.
Related to https://github.com/bpmn-io/bpmn-js-examples/issues/112
> Update examples to bpmn-js@7

- properties-panel-extension/README.md
- properties-panel-extension/app/provider/magic/MagicPropertiesProvider.js
- properties-panel-extension/app/provider/magic/parts/SpellProps.js
- properties-panel-extension/package.json
__Which issue does this PR address?__
Closes #123 
__Acceptance Criteria__
__Definition of Done__
> Update Properties Panel Extension Example

- properties-panel-extension/package.json
__Which issue does this PR address?__
Closes #128
Ensures peer-dependencies are met.
__Acceptance Criteria__
__Definition of Done__
> chore(properties-panel-extension): bump dependencies

- properties-panel-extension/README.md
- properties-panel-extension/app/index.js
- properties-panel-extension/app/provider/magic/MagicPropertiesProvider.js
- properties-panel-extension/app/provider/magic/index.js
- properties-panel-extension/package.json
- properties-panel/package.json
> Update Properties Panel Examples

- properties-panel-extension/package.json
- properties-panel/package.json
> chore: update properties-panel examples

- colors/README.md
> chore: use hex values for colors

- README.md
> docs: add svelte-bpmn to examples

- properties-panel-extension/README.md
> chore(properties-panel-extension): add link to the old version

- properties-panel-extension/README.md
Move compatibility notice to top; this is how we usually do it.
> docs(README): minor improvement

- colors/index.html
> fix: colors example now uses valid opaque color

- properties-panel-async-extension/app/provider/magic/parts/SpellProps.js
- properties-panel-async-extension/package.json
- properties-panel-extension/README.md
- properties-panel-extension/app/provider/magic/parts/SpellProps.js
- properties-panel-extension/package.json
- properties-panel/package.json
> feat: migrate properties panel examples to v1.0.0-alpha.5

- custom-bundle/package.json
- custom-bundle/rollup.config.js
- theming/package.json
- theming/rollup.config.js
> Upgrade rollup

- bpmn-properties/README.md
- colors/README.md
- colors/index.html
- commenting/README.md
- custom-elements/README.md
- custom-meta-model/README.md
- custom-modeling-rules/README.md
- interaction/README.md
- modeler/README.md
- modeling-api/app/snippets/businessObjects.js
- overlays/README.md
- pre-packaged/README.md
- properties-panel/README.md
- starter/README.md
- theming/README.md
- theming/index.html
- url-viewer/README.md
This supports our `master` to `main` transition.
> Update references to `main`

- properties-panel-list-extension/app/provider/magic/parts/ExtensionList.js
- properties-panel-list-extension/package.json
related to https://forum.bpmn.io/t/need-help-in-integrating-bpmn-property-panel-extension-list-with-angular/10027
> chore(list-extension): use html instead of JSX

- properties-panel-extension/README.md
- properties-panel-extension/app/provider/magic/MagicPropertiesProvider.js
- properties-panel-extension/app/provider/magic/parts/SpellProps.js
Related to https://forum.bpmn.io/t/adding-tooltip-in-property-panel/10113
> feat: add tooltips to the properties panel extension

- commenting/package.json
- custom-meta-model/package.json
- deep-linking/package.json
- i18n/package.json
- minimap/package.json
- modeler/package.json
- overlays/package.json
- package-lock.json
- transaction-boundaries/package.json
> fix: add missing *-loader dependencies

- bpmn-properties/package.json
- bundling/package.json
- commenting/package.json
- custom-meta-model/package.json
- custom-modeling-rules/package.json
- deep-linking/package.json
- i18n/package.json
- minimap/package.json
- modeler/package.json
- modeling-api/package.json
- overlays/package.json
- package-lock.json
- properties-panel-async-extension/package.json
- properties-panel-extension/package.json
- properties-panel-list-extension/package.json
- properties-panel/package.json
- transaction-boundaries/package.json
Fix outdated dependency.
To ensure you provided everything we need to look at your PR:
> chore: fix dependency

- bpmn-properties/package.json
- bundling/package.json
- commenting/package.json
- custom-bundle/package.json
- custom-meta-model/package.json
- custom-modeling-rules/package.json
- deep-linking/package.json
- i18n/package.json
- minimap/package.json
- modeler/package.json
- modeling-api/package.json
- overlays/package.json
- package-lock.json
- package.json
- properties-panel-async-extension/package.json
- properties-panel-extension/package.json
- properties-panel-list-extension/package.json
- properties-panel/package.json
- theming/package.json
- transaction-boundaries/package.json
- types/package.json
Follow-up to https://github.com/bpmn-io/bpmn-js-examples/pull/289.
To ensure you provided everything we need to look at your PR:
> Housekeeping

- embedding/src/app.js
- embedding/src/index.html
Allows to try out keyboard shortcuts in a more advanced scenario.
Related to https://github.com/bpmn-io/bpmn.io/pull/209
To ensure you provided everything we need to look at your PR:
> feat(embedding): feature shared clipboard
